name: 'Build and upload distribution'
# Builds the action distribution an uploads as an artifact for later download
runs:
  using: "composite"
  steps: 
    - name: Build distribution
      shell: bash
      run: |
        npm install
        npm run build
    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/

